### ISSUE TITLE
Log Levels Appear to be Ignored

### ISSUE THREAD

**Issue by FranticPanic** [mastiffmushroom/TrackerAutoLogin#18]
Hopefully I'm not making a silly user error here, but I seem to be having some issues regarding the logging when running the container.

I'm running this via the UnRaid Docker found under the community apps page.

When setting the log levels from `debug` to `error` it appears that the log level function is having issues. Additionally, setting logs from `stderr` to `file` creates the log file, but does not actually put anything into the log file.
Reverting `LogLevel` back to debug prevents the errors below from continuing and the 'file' option begins to work as expected (log file generated and logs show within the file).

Since passwords don't seem to be encrypted or redacted in the log output, I will only share the errors I see immediately.
I'm also greeted with a wall of red text, I'm assuming this is the requested webpages source, but is difficult to tell in the unraid console and copying pasting into notepad++ doesn't seem to return any valuable information (possible failing login attempt, request, etc).
If you'd like the full logs, I can redact the passwords and share them with you via Discord and I will do my best to get back to you as soon as possible.

This is with the `LogLevel` set to 'error' and `LogType` set to `stderr`
First logging error
```
Traceback (most recent call last):
  File "./app.py", line 12, in <module>
    from custom_logger import logging
  File "/app/custom_logger.py", line 26, in <module>
    logging.basicConfig(logging=logging.ERROR, stream=sys.stdout)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): logging
```

Second error
```
File "./app.py", line 12, in <module>
    from custom_logger import logging
  File "/app/custom_logger.py", line 26, in <module>
    logging.basicConfig(logging=logging.ERROR, stream=sys.stdout)
DEBUG:urllib3.connectionpool:http://127.0.0.1:54665 "POST /session/884954f71803f8528183abc62ccbe869/execute/sync HTTP/1.1" 200 14
  File "/usr/local/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
```

**Comment by digitalgp** [comment]
Setting it ut error gives that error code, warning works. But displays way to much still..
